name: Build executables

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Windows EXE
        run: |
          pyinstaller backend\main.py --name Buzzer-Insagora --onefile --collect-submodules backend --collect-all bleak --hidden-import bleak.backends.winrt.client --add-data "backend\GUI\static;backend\GUI\static" --add-data "backend\backend-config.json;backend"

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: Buzzer-Insagora-Windows
          path: dist/Buzzer-Insagora.exe

  build-linux:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libssl-dev \
            libffi-dev \
            zlib1g-dev \
            wget \
            libbz2-dev \
            libreadline-dev \
            libsqlite3-dev \
            xz-utils \
            tk-dev \
            uuid-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libgdbm-dev \
            liblzma-dev

      - name: Download Python 3.14 source
        run: |
          wget https://www.python.org/ftp/python/3.14.0/Python-3.14.0.tgz
          tar -xf Python-3.14.0.tgz

      - name: Build and install Python
        run: |
          cd Python-3.14.0
          ./configure --enable-optimizations --with-ensurepip=install
          make -j$(nproc)
          sudo make altinstall
          python3.14 --version

      - name: Install python deps
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Linux binary
        run: |
          pyinstaller backend/main.py \
            --name Buzzer-Insagora \
            --onefile \
            --collect-submodules backend \
            --collect-all bleak \
            --add-data "backend/GUI/static:backend/GUI/static" \
            --add-data "backend/backend-config.json:backend"

      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: Buzzer-Insagora-Linux
          path: dist/Buzzer-Insagora
